heat_template_version: 2015-10-15
description: Create and associate security groups to an instance

resources:
  web_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443

  instance_port:
    type: OS::Neutron::Port
    properties:
      network: public
      security_groups:
        - default
        - { get_resource: web_secgroup }
      fixed_ips:
        - subnet_id: "c2fcc191-c8e9-48cd-912a-df3f5ea75b72"

  instance:
    type: OS::Nova::Server
    properties:
      flavor: m1.small
      image: CentOS-6.6_x86-64-swift
      networks:
        - port: { get_resource: instance_port }