#!/bin/bash
LOCK_FILE=/var/iib/puppet/state/agent_catalog_run.lock
DISABLE_FILE=/var/lib/puppet/state/agent_disabled.lock
#Define Value 
LAST_RUN_TIME=`cat /var/lib/puppet/state/last_run_summary.yaml | grep last_run  | awk {'print $2'}`
DATE=`date -d "1970-01-01 UTC $LAST_RUN_TIME seconds" "+%Y-%m-%dT%H:%M"`
RUNLOG=`egrep 'failure|failed|failed_to_restart' /var/lib/puppet/state/last_run_summary.yaml|grep -v ': 0' >/dev/null 2>&1 && echo 0 || echo 1`
MESSAGES=`egrep "$DATE" /var/log/messages 2>/dev/null |egrep  'puppet-agent.*502 Bad Gateway'  >/dev/null 2>&1  && echo 0 || echo 1`
VPN_NETWORK=`ping -c 1 puppet.0.uc.ustack.in  >/dev/null 2>&1 && echo 1 || echo 2`

#puppet agent for method
PUPPET_AGENT(){

      if [ ! -f $LOCK_FILE ];then
             /usr/bin/puppet agent -vt  >/dev/null 2>&1;
      exit 0
  fi
}


#Network judge
if [ $VPN_NETWORK  -eq 2 ];then

   echo 2

#Disable judge
elif [ -f $DISABLE_FILE ];then

   echo 3

#It will be check Some failure and double acknowledge
elif [ $RUNLOG -eq 0 -a $MESSAGES -eq 1 ];then

   echo 0
   PUPPET_AGENT

else

   echo 1

fi
