#!/usr/bin/python
import commands
import json
import sys

poolname = sys.argv[1]

if __name__ == '__main__':
    status, output = commands.getstatusoutput("ceph df -f json")
    ceph_df = json.loads(output)
    pools = ceph_df['pools']
    for pool in pools:
        if pool['name'] == poolname:
            print pool['stats']['kb_used']

