#!/bin/bash
# wuxiaoliu

[[ $2 ]] ||  exit

if [ "$1" == "status" ]
then
    ping -w 2 -c 2 $2 2>/dev/null |egrep  -q 'received, 0% packet loss' && echo 1 || echo 0

elif [ "$1" == "sec" ]
then
    if ping -w 2 -c 2 $2 2>/dev/null | grep avg >/dev/null;then ping -w 2 -c 2 $2 2>/dev/null | grep avg | cut -d '/' -f5;else echo 9999;fi
    #ping -w 2 -c 2 $2 2>/dev/null | grep avg | cut -d '/' -f5

elif [ "$1" == "bigloss" ]
then
    ping -w 2 -c 2 $2 2>/dev/null | grep 'packet loss' | cut -d % -f1 | awk -F ' ' ' {print ($(NF) )}'
    #ping -i 0.1 $2 -c 10 -s 1472 2>/dev/null |grep 'packet loss' | awk '{print $6}' | cut -d % -f1

elif [ "$1" == "loss" ]
then
    ping -w 2 -c 2 $2 2>/dev/null | grep 'packet loss' | cut -d % -f1 | awk -F ' ' ' {print ($(NF) )}'
    #ping -w 3 -c 2 $2 2>/dev/null |grep 'packet loss' | awk '{print $6}' | cut -d % -f1
    #ping -w 3 -c 2 $2 2>/dev/null |grep 'packet loss' |sed -r 's/(.*,)(.*)(%.*)/\2/'|xargs
fi
