#!/usr/bin/python
import commands
import sys

cpu_num_global = sys.argv[1] 

def judge_cpu_is_kvm():
    status, cpus = commands.getstatusoutput('pidstat | grep qemu-kvm')
    cpus = cpus.split("\n")  
    for cpu in cpus:
        piddata = cpu.split()
        application = piddata[7]
        cpu_num = piddata[6]
        if cpu_num_global == cpu_num:
             return 1
    return 0

if __name__ == "__main__":
    print judge_cpu_is_kvm()

