#!/usr/bin/python
import commands
import json
import sys

keyword = sys.argv[1]
mon_name = sys.argv[2]

def mon_health_status(ceph_data, mon_name):
    mon_healths = ceph_data['health']['health']['health_services'][0]['mons']
    for mon_health in mon_healths:
        if mon_health['name'] == mon_name:
            return mon_health['health']

def pg_state(ceph_data):
    pgmap = ceph_data['pgmap']
    pgs_by_state = pgmap['pgs_by_state']
    for pgstate in pgs_by_state:
        if pgstate['state_name'] == "active+clean":
            return pgstate['count']

def time_check(ceph_data, mon_name):
    time_checks = ceph_data['health']['timechecks']
    for time_check in time_checks['mons']:
        if time_check['name'] == mon_name:
            return time_check['health']

def check_status(status):
    if status == "HEALTH_OK":
        print 1
    elif status == "HEALTH_WARN":
        print 0
    else:
        print -1
if __name__ == "__main__":
    (status, ceph_data) = commands.getstatusoutput('ceph -s -f json')
    ceph_data = json.loads(ceph_data)

    if keyword == "mon_health":
        status = mon_health_status(ceph_data, mon_name)
        check_status(status)
    elif keyword == "overall_status":
        status = ceph_data['health']['overall_status']
        check_status(status)
    elif keyword == "osd_map":
        osdmap = ceph_data['osdmap']['osdmap']
        if str(osdmap['num_in_osds']) != str(osdmap['num_up_osds']):
            print 0
        else:
            print 1
    elif keyword == "osd_diff":
        osdmap = ceph_data['osdmap']['osdmap']
        if int(osdmap['num_osds']) - int(osdmap['num_in_osds']) > 3 or int(osdmap['num_osds']) - int(osdmap['num_up_osds']) > 3:
            print -1
        else:
            print 1
    elif keyword == "pg_state":
        if pg_state('ceph_data') == 4096:
            print 1
        else:
            print 0
    elif keyword == 'time_check':
        status = time_check(ceph_data, mon_name)
        check_status(status)
