#!/usr/bin/python
import os
import json
import sys

node_list = ["server-64", "server-65"]

if __name__ == "__main__":
    data = []
    for node in node_list:
        data.append({"{#NodeNAME}": node})
    output = {"data": data}
    print json.dumps(output)
