#!/bin/bash
#the script Statistics error 500 per minute
#author:jiayun
#change by wxl,this script use in UOS2.0 , 3.0 no nginx
web_path=/var/log/nginx/placebo_https_access.log
web_path1=/var/log/nginx/tars_http_access.log
web_path2=/var/log/nginx/ustack-www_access.log
now_date=`date +%d/%b/%Y:%H:%M`
#date="`date +%d`/`date +%b`/`date +%Y:%H:%M`"
date="`date +%d`/`date +%b`/`date -d '1 minute ago' +%Y:%H:%M`"
if [ $# == 2 ];then
    if [ $1 = "placebo_https" -a $2 = "500" ];then
        if [ -e ${web_path} ];then
            num=`tail -n 1500 ${web_path} |egrep $date | egrep "\"\ 5[0-9][0-9]\ "|sed -n '1p'`
            if [ -n "$num" ];then
                error_code=`tail -n 1500 ${web_path} |egrep $date | egrep -o "\"\ 5[0-9][0-9]\ "|tr -d '" '|awk '{a[$1]++}END{for (j in a) print "code:"j,"num:"a[j]}'`
                echo -e "\n【$error_code】\n $num"
            else
                echo 0
            fi
        else
            echo -1
        fi
    elif [ $1 = "tars_http" -a $2 = "500" ];then
        if [ -e ${web_path1} ];then
            num=`tail -n 1500 ${web_path1} |egrep $date | egrep "\"\ 5[0-9][0-9]\ "|sed -n '1p'`
            if [ -n "$num" ];then
                error_code=`tail -n 1500 ${web_path1} |egrep $date | egrep -o "\"\ 5[0-9][0-9]\ "|tr -d '" '|awk '{a[$1]++}END{for (j in a) print "code:"j,"num:"a[j]}'`
                echo -e "\n【$error_code】\n $num"
            else
                echo 0
            fi
        else
            echo -1
        fi
    fi
elif [ $# == 3 ];then
    if [ $1 = "ustack-www" -a $2 = "404" -a $3 = "500" ];then
        if [ -e ${web_path2} ];then
            num=`tail -n 1500 ${web_path2} |egrep $date | egrep "\/accounts\/sms\/.*\ 404\ |\"\ 5[0-9][0-9]\ "|sed -n '1p'`
            if [ -n "$num" ];then
                error_code=`tail -n 1500 ${web_path2} |egrep $date | egrep -o "\/accounts\/sms\/.*\ 404\ |\"\ 5[0-9][0-9]\ "|egrep -o "\" 404 |\" 5[0-9][0-9] "|tr -d '" '|awk '{a[$1]++}END{for (j in a) print "code:"j,"num:"a[j]}'`
                echo -e "\n【$error_code】 \n $num"
            else
                echo 0
            fi
        else
            echo -1
        fi
    elif [ $1 = "placebo_https" -a $2 = "500" -a $3 = "five" ];then
        for i in `seq 0 5` ;do egrep `date +%d/%b/%Y:%H:%M --date=" $i minutes ago"` $web_path | egrep "\"\ 5[0-9][0-9]\ ";done |wc -l
    elif [ $1 = "tars_http" -a $2 = "500" -a $3 = "five" ];then
        for i in `seq 0 5` ;do egrep `date +%d/%b/%Y:%H:%M --date=" $i minutes ago"` $web_path1 | egrep "\"\ 5[0-9][0-9]\ ";done |wc -l
    fi
else
    echo "argument Error eg: ./zabbix-error-log placebo_https 500"
fi
