#!/usr/bin/python

import json
import commands

if __name__ == "__main__":
    (status, output) = commands.getstatusoutput('cat /proc/cpuinfo | grep processor | wc -l')
    cpus = int(output)
    content = []
    for i in range(0, cpus):
        content.append({"{#CPUNUM}": i})
    result = {"data": content}
    print json.dumps(result, sort_keys=True, indent=4, separators=(',', ': '))
