#!/usr/bin/python

import requests
import sys

def check_openstack_api(url, resource):
    r = requests.get("%s/os/%s/" % (url, resource))
    if r.status_code == 300 or r.status_code == 200:
        if "versions" in r.json():
            print r.json()['versions']
        else:
            print "api is not available"
    else:
        print "api is not available"


if __name__ == "__main__":
    check_openstack_api(sys.argv[1], sys.argv[2])
