#!/usr/bin/python
import os
import json


if __name__ == "__main__":
    data = []
    disks = os.popen("dmidecode -t system | awk '/Product Name:/{print $NF}'").readlines()
    data.append({"{#MACHINETYPE}": disks[0].strip('\n')})
    output = {"data": data}
    print json.dumps(output)
