#!/bin/bash
prefix=`facter ipaddress_eth0 | cut -d "." -f1-3`
ip_38=$prefix".38"
ip_37=$prefix".37"
ping -c 1 -W 1 $ip_37 > /dev/null
re_37=`echo $?`
ping -c 1 -W 1 $ip_38 > /dev/null
re_38=`echo $?`
if [[ $re_37 = "1" || $re_38 = "1" ]]
then
    echo "0"
else
    echo "1"
fi

