#!/usr/bin/python
import os
import json
#create by UOS2.0
#change by wxl

if __name__ == "__main__":
    data = []
    disks = os.popen("ls -l /dev/md[0-9] 2>/dev/null| awk '{print $NF}'").readlines()
    for disk in disks:
        diskname = disk.strip('\n')
        diskshortname = diskname[5:]
        data.append({"{#DISKNAME}": diskname, "{#SHORTDISKNAME}": diskshortname})
    output = {"data": data}
    print json.dumps(output)
