#!/usr/bin/python
import os
import json
import sys

devicetype = sys.argv[1]


if __name__ == "__main__":
    data = []
    if devicetype != "tap":
        netdevices = os.popen("ifconfig | awk '/"+ devicetype + "/{ETH=$1;print ETH}'").readlines()
        for netdevice in netdevices:
            netdevicename = netdevice.strip('\n')
            data.append({"{#IFNAME}": netdevicename, "{#IFNAME1}": netdevicename, "{#IFNAME2}": netdevicename})
    else:
        tapdevices = os.popen("cat /tmp/tapdata").readlines()
        for tapdevice in tapdevices:
            devices = tapdevice.strip("\n").split()
            if len(devices) !=0 and devices[1] == "0":
                data.append({"{#IFNAME}": devices[0], "{#IFNAME1}": devices[0], "{#IFNAME2}": devices[0]})
    output = {"data": data}
    print json.dumps(output)
