#!/bin/bash
number=$1
way=$2
memTotal=`cat /proc/meminfo |grep "^MemTotal"|awk '{print $2}'`
memFree=`cat /proc/meminfo |grep "^MemFree"|awk '{print $2}'`
buffers=`cat /proc/meminfo |grep "^Buffers"|awk '{print $2}'`
cached=`cat /proc/meminfo |grep "^Cached"|awk '{print $2}'`
#echo "$memTotal,$memFree,$buffers,$cached"
available=`expr $memFree + $buffers + $cached`
#echo $available,$memTotal
percent=`awk 'BEGIN{printf "%.2f\n",('$available'/'$memTotal')}'`
server=(httpd openstack-cinder-volume neutron-server openstack-nova-api ustack-gring-checker)
if [ `expr $percent \> $number` -eq 0 ];
then
    for i in ${server[*]}
    do
        service $i $way > /dev/null 2>&1
        sleep 0.2
        end=`service $i status | grep running | wc -l`
        if [ $end -eq 0 ];then
            echo -1
            exit
        fi
    done
    echo 0            #reload sucess
else
    echo 1            #normal
fi
