#!/bin/bash
one=$1
msg_num=`dmesg |grep "NIC Link" |wc -l`
eth2_stat=`ip l show dev eth2`
eth2_Stat=`ip l show dev eth2|egrep -o "stat.*mode" |awk '{print $2}'`
eth2_rx_error=`ethtool -S eth2|grep "rx_errors"|awk '{print $2}'`
eth2_rx_missed_error=`ethtool -S eth2|grep "rx_missed_errors"|awk '{print $2}'`
eth2_link=`ethtool eth2|grep "Link"|awk '{print $NF}'`
date=`date +%Y-%m-%d\ %k:%M:%S`
if [[ $one == "rx_error" ]];then
    echo $eth2_rx_error
elif [[ $one == "rx_missed_error" ]];then
    echo $eth2_rx_missed_error
elif [[ $one == "link" ]];then
    if [[ $eth2_link == "yes" ]];then
        echo 1
    else
        echo 0
    fi
elif [[ $one == "message" ]];then
    echo $msg_num
elif [[ $one == "stat" ]];then
    if [[ $eth2_Stat == "UP" ]];then
        echo 1
    else
        echo 0
    fi
fi
