#!/usr/bin/python

import subprocess
import sys

LAST_FILE = '/tmp/last.txt'
FIX_FILE = '/tmp/ssdb.txt'


if __name__ == "__main__":
    last = {}
    curr = {}
    write = {}
    try:
        f = open(LAST_FILE, 'r')
        for line in f.readlines():
            k, v = line.split(',')
            last[k] = int(v)
        f.close()
    except:
        pass

    handle = subprocess.Popen("ssdb-cli -p 8887 << EOF\ninfo cmd\nEOF",
                              shell=True, stdout=subprocess.PIPE)
    lines = handle.stdout.read().split('\n')
    for keyword in ['set', 'get', 'clear', 'scan']:
        key = "cmd.h%s" % keyword
        i = 0
        for line in lines:
            i += 1
            if key == line:
                break
        assert(i < len(lines))
        call, wait, proc = lines[i].strip().split('\t')
        curr[keyword+"-call"] = int(call.split()[1])
        curr[keyword+"-wait"] = int(wait.split()[1])
        curr[keyword+"-proc"]= int(proc.split()[1])
        call_diff = curr[keyword+"-call"]-last.get(keyword+"-call", 0)
        if call_diff != 0:
            write[keyword+"-wait"] = float(curr[keyword+"-wait"]-last.get(keyword+"-wait", 0))/call_diff
            write[keyword+"-proc"] = float(curr[keyword+"-proc"]-last.get(keyword+"-proc", 0))/call_diff

    handle = subprocess.Popen("ssdb-cli -p 8887 << EOF\ninfo\nEOF",
                              shell=True, stdout=subprocess.PIPE)
    lines = handle.stdout.read().split('\n')
    for keyword in ['links', 'total_calls']:
        i = 0
        for line in lines:
            i += 1
            if keyword == line:
                break
        assert(i < len(lines))
        write[keyword] = int(lines[i].strip())
    
    bl = []
    for k, v in write.items():
        bl.append("%s,%s" % (k, v))
    
    f = open(FIX_FILE, 'w')
    f.write("\n".join(bl))
    f.close()

    bl = []
    for k, v in curr.items():
        bl.append("%s,%s" % (k, v))

    f = open(LAST_FILE, 'w')
    f.write("\n".join(bl))
    f.close()
    print 1
