#!/bin/bash

exec_mysql_cmd() {
   local host=$1
   shift
   local cmd=$@
   mysql -e "${cmd}"
}

read_slave_state() {
    local host=$1
    local field=$2
    exec_mysql_cmd ${host} 'show slave status\G' | grep ${field} | awk '{print $2}'
}

## check if slave is active
io_thread_running=$(read_slave_state 127.0.0.1 Slave_IO_Running)
if [[ "$io_thread_running" != "Yes" ]]; then
#    echo "IO thread is NOT running!"
    echo -1
    exit -1 
fi

sql_thread_running=$(read_slave_state 127.0.0.1 Slave_SQL_Running)
if [[ "$sql_thread_running" != "Yes" ]]; then
#    echo "SQL thread is NOT running!"
    echo -2
    exit -2
fi

seconds_behind=$(read_slave_state 127.0.0.1 Seconds_Behind_Master)
if [ "$seconds_behind" = "NULL" ]; then
#    echo "There are something wrong though the IO and SQL thread is running."
    echo -3
    exit -3
elif [ "$seconds_behind" -gt 10 ]; then
#    echo "The Gap betwee master and slave is great than 10, this is not normal."
    echo -4
    exit -4
else
#    echo "Slave is running active"
    echo 0
    exit 0
fi
