#!/bin/bash
#change by wxl,this script use to UOS2.0 ,so nu used in UOS3.0 monitor
#/etc/init.d/ can used by zabbux user, so no need sudo
status=`/etc/init.d/openstack-cinder-volume status |grep -i "(pid" |wc -l`

if [[ $status -eq 0 ]];then
    /etc/init.d/openstack-cinder-volume stop >/dev/null 2>&1
    killall -9 cinder-volume
    /etc/init.d/openstack-cinder-volume restart >/dev/null 2>&1
    [[ $? -eq 0 ]] && echo 0 ||echo -1
else
    echo 1
fi
