#!/bin/env python
from __future__ import division
import subprocess
import sys
import commands
one=sys.argv[1]
two=sys.argv[2]
def systemfile(number):
    status,output=commands.getstatusoutput("cat /proc/sys/fs/file-nr")
    if status == 0:
        use=output.split()[0]
        nuse=output.split()[-1]
        print '%0.2f'%(int(use)/int(nuse))
def sectionfile(number,):
    result=subprocess.Popen("pgrep -f qemu-kvm",shell=True, stdout=subprocess.PIPE)
    sum=0
    for num in result.stdout.readlines():
        status,output=commands.getstatusoutput("cat /proc/%s/limits | grep files | awk '{print $4}'"%num.strip())
        tote=output.strip()
        status,output=commands.getstatusoutput("ls /proc/%s/fd/ | wc -l"%num.strip())
        open=output.strip()
       # print tote,open,'%0.2f'%(int(open)/int(tote))
        value='%0.2f'%(int(open)/int(tote))
        if value >= number:
            sum=sum+1
    print sum
if __name__ == "__main__":
    if one == "all":
        systemfile(two)
    elif one == "section":
        sectionfile(two)

