#!/bin/bash

LOGPATH="/var/log/nova/conductor.log"

test -s $LOGPATH || { echo 100 ; exit  ; } 

DATE=`date -d "1 minute ago" +"%Y-%m-%d %H:%M"`

RUNLOG=`egrep "$DATE" $LOGPATH 2>/dev/null |grep 'Timed out waiting for a reply to message ID' >/dev/null 2>&1 && echo 0 || echo 1`

echo $RUNLOG
