#!/bin/bash
prefix=`facter ipaddress_eth0 | cut -d "." -f1-3`
ip_33=$prefix".33"
ip_34=$prefix".34"
ping -c 1 -W 1 $ip_33 > /dev/null
re_33=`echo $?`
ping -c 1 -W 1 $ip_34 > /dev/null
re_34=`echo $?`
if [[ $re_33 = "1" || $re_34 = "1" ]]
then
    echo "0"
else
    echo "1"
fi

