#!/bin/env python
import subprocess
import sys,commands
import datetime,os
import commands,sys
one=sys.argv[1]
server=sys.argv[2]
reload=sys.argv[3]
if __name__ == "__main__":
    command="tail -1 /var/log/nova/compute.log | awk '{print $1,$2}'"
    hand = subprocess.Popen(command,shell=True, stdout=subprocess.PIPE)
    band_name=hand.stdout.read().strip()
    time=band_name.split('.')[0]
    time1=datetime.datetime.strptime(time, '%Y-%m-%d %H:%M:%S')
    time2=datetime.datetime.now()
    timedelta= time2 - time1
    time_delay=timedelta.days*24*3600 + timedelta.seconds
    if int(time_delay) > int(one):
        status,output=commands.getstatusoutput('service %s %s'%(server,reload))
        if status == 0 and output != "":
            print 0
        else:print -1
    else:
        print 1
