#!/bin/bash
#####################################
##  log monitor script for zabbix
##     written by zhangxian
##      on 2016-03-22 23:30
####################################

log_time1=$(date -d '1 min ago' +'%Y-%m-%d %H:%M:')
log_time2=$(date -d '1 min ago' +'%d/%b/%Y:%H:%M:')

function usage(){
  echo "Usage: sh $0 log_path key"
  echo "       log_path:    input the log_path,you must input the absolute path"
  echo "       key:         input the key you want monior,you can input a word or some words,with some words you must add quotes"
  echo "       version:     show the version"
  echo "       help:        show the usage"
  echo "Example: sh $0 /var/log/nova/api.log ERROR"
  echo "Written by Zhangxian"
  exit 0;
}

function version(){
  echo "Version 2.0"
  exit 0;
}

function help(){
  usage;
}

function get_counts_by_logpath() {
  local log_path=$1
  local keys=$2
  local log_date_result=$(grep "${log_time1}\|${log_time2}" "${log_path}" 2>/dev/null)
  if [ ! -z "${log_date_result}" ];then
    keys_count=$(echo "${log_date_result}"|grep -c "${keys}")
  else
    keys_count=0;
  fi
  echo "${keys_count}"
}

if [ $# -lt 2 ];then
  usage;
fi

log_path=$1;
shift 1;
keys=$*;
get_counts_by_logpath ${log_path} ${keys}

